version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/client"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/7.0"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/8.0"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/9.0/flat"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/9.0/rc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/flat-config-fail"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/flat-config-mjs"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/flat-config"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/load-eslint"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/playgrounds/ts"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase
